##########Pipeline###########
# Enter your protein and RNA sequence of interest (in plain text format):
protSeq <- "YOURPROTEINSEQUENCEGOESHERE"
rnaSeq  <- "YOURRNASEQUENCEGOESHERE"

# Example sequences; delete the '#' at the beginning of the line to enter these
#protSeq <- "MEELVVEVRGSNGAFYKAFVKDVHEDSITVAFENNWQPDRQIPFHDVRFPPPVGYNKDINESDEVEVYSRANEKEPCCWWLAKVRMIKGEFYVIEYAACDATYNEIVTIERLRSVNPNKPATKDTFHKIKLDVPEDLRQMCAKEAAHKDFKKAVGAFSVTYDPENYQLVILSINEVTSKRAHMLIDMHFRSLRTKLSLIMRNEEASKQLESSRQLASRFHEQFIVREDLMGLAIGTHGANIQQARKVPGVTAIDLDEDTCTFHIYGEDQDAVKKARSFLEFAEDVIQVPRNLVGKVIGKNGKLIQEIVDKSGVVRVRIEAENEKNVPQEEEIMPPNSLPSNNSRVGPNAPEEKKHLDIKENSTHFSQPNSTKVQRVLVASSVVAGESQKPELKAWQGMVPFVFVGTKDSIANATVLLDYHLNYLKEVDQLRLERLQIDEQLRQIGASSRPPPNRTDKEKSYVTDDGQGMGRGSRPYRNRGHGRRGPGYTSGTNSEASNASETESDHRDELSDWSLAPTEEERESFLRRGDGRRRGGGGRGQGGRGRGGGFKGNDDHSRTDNRPRNPREAKGRTTDGSLQIRVDCNNERSVHTKTLQNTSSEGSRLRTGKDRNQKKEKPDSVDGQQPLVNGVP"
#rnaSeq  <- "GGGGGGTGATTGGAAGGGAGGGAGGTG"


# Give the path to the .diso file from DISOPRED; run the code to get a prompt to select the file.
disoFile <- file.choose()

# Set the working directory to the location of your RPIDisorder folder
setwd(choose.dir())

# Give the name you want for the ARFF file:
arffName <- "NameHere"

# Run this line of code, as is. This will generate an ARFF file.
writeSpArff(getRpiDisorderArff(protSeq, rnaSeq, disoFile), paste0(arffName, ".arff"), appending = FALSE)

